JIRA- Update commit_checker.yml

diff --git a/.github/workflows/commit_checker.yml b/.github/workflows/commit_checker.yml
--- a/.github/workflows/commit_checker.yml
+++ b/.github/workflows/commit_checker.yml
@@ -23,10 +23,10 @@ jobs:
         run: |
           commit_message=$(git log --format=%s -n 1 ${{ github.sha }})
           echo $commit_message
-          jira_pattern="\\bJIRA-\\d+\\b"
+          jira_pattern="JIRA-""
 
-          if [[ ! $commit_message =~ $jira_pattern ]]; then
-            echo "Error: Commit message must have a valid JIRA ticket ID."
-            exit 1
-          fi
+           if [[ ! $commit_message =~ $jira_pattern ]]; then
+             echo "Error: Commit message must contain 'JIRA-'."
+             exit 1
+           fi
 
